builds:
  - ldflags:
    - -s -w -X github.com/harnash/mediawiki-cli/cmd.version={{.Version}} -X github.com/harnash/mediawiki-cli/cmd.commit={{.Commit}} -X github.com/harnash/mediawiki-cli/cmd.date={{.Date}}